const DATA=window.__KEC_DATA__;
if(!DATA||!DATA.training){document.body.innerHTML="<div style='padding:24px;color:#00ff87'>Training data failed to load. Refresh once.</div>";throw new Error("KEC DATA missing");}
const PATHS=Array.isArray(DATA.paths)?DATA.paths:[];
const TRAINING=DATA.training||{};
const KEY="hoodboss-kec-training-v12";
const MEMORY={value:null};
const STORAGE=(function(){try{localStorage.setItem("__t","1");localStorage.removeItem("__t");return localStorage;}catch(e){return null;}})();
function readSaved(){try{if(STORAGE){var c=STORAGE.getItem(KEY);if(c)return c;}return MEMORY.value;}catch(e){return MEMORY.value;}}
function writeSaved(v){MEMORY.value=v;try{if(STORAGE)STORAGE.setItem(KEY,v);}catch(e){}}
function validPath(id){return PATHS.some(function(p){return p.id===id;})&&TRAINING[id]&&(TRAINING[id].modules||[]).length;}
var DEFAULT_PATH="new-tech";
function defaultPathId(){if(validPath(DEFAULT_PATH))return DEFAULT_PATH;var hit=PATHS.filter(function(x){return validPath(x.id);})[0];return hit?hit.id:(PATHS[0]&&PATHS[0].id);}
function blankState(){var pid=defaultPathId();return{path:pid,module:((TRAINING[pid]&&TRAINING[pid].modules&&TRAINING[pid].modules[0])||{}).id||null,progress:{}};}
function load(){try{var raw=readSaved(),x=raw?JSON.parse(raw):null,base=blankState();if(!x||typeof x!=="object")return base;var m=Object.assign(base,x);var mgr=false;try{mgr=sessionStorage.getItem("hb-kec-mgr")==="1";}catch(e){}
if(!mgr||!validPath(m.path)){m.path=defaultPathId();var mods=(TRAINING[m.path]&&TRAINING[m.path].modules)||[];if(!mods.some(function(z){return z.id===m.module;}))m.module=mods[0]?mods[0].id:null;}return m;}catch(e){return blankState();}}
var state=load();
var activePath=validPath(state.path)?state.path:blankState().path;
var activeModule=((TRAINING[activePath]&&TRAINING[activePath].modules)||[]).some(function(m){return m.id===state.module;})?state.module:(((TRAINING[activePath]&&TRAINING[activePath].modules)||[])[0]||{}).id||null;
function save(){state.path=activePath;state.module=activeModule;writeSaved(JSON.stringify(state));}
function pathData(){return PATHS.filter(function(p){return p.id===activePath;})[0];}
function modules(){return (TRAINING[activePath]&&TRAINING[activePath].modules)||[];}
function moduleData(){var list=modules();return list.filter(function(m){return m.id===activeModule;})[0]||list[0];}
function moduleKey(mid){return activePath+"::"+mid;}
function getChecks(mid){return state.progress[moduleKey(mid)]||{};}
function moduleDone(mid){var m=modules().filter(function(x){return x.id===mid;})[0];if(!m)return false;var s=getChecks(mid);if(m.quiz)return isFinite(s.score)&&s.score>=80;if(m.signoff)return!!s.signoff;var c=(m.sections||[]).reduce(function(a,z){return a.concat(z[2]||[]);},[]);return c.length>0&&c.every(function(_,i){return s[i];});}
function moduleDoneGlobal(pid,mid){var m=((TRAINING[pid]||{}).modules||[]).filter(function(x){return x.id===mid;})[0];if(!m)return false;var s=state.progress[pid+"::"+mid]||{};if(m.quiz)return isFinite(s.score)&&s.score>=80;if(m.signoff)return!!s.signoff;var c=(m.sections||[]).reduce(function(a,z){return a.concat(z[2]||[]);},[]);return c.length>0&&c.every(function(_,i){return s[i];});}
function allStats(){var ms=0,done=0,checked=0;PATHS.forEach(function(p){((TRAINING[p.id]||{}).modules||[]).forEach(function(m){ms++;if(moduleDoneGlobal(p.id,m.id))done++;});});return{ms:ms,done:done,checked:checked};}
function esc(x){return String(x==null?"":x).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;");}
function toast(msg){var t=document.getElementById("toast");if(!t)return;t.textContent=msg;t.classList.add("show");clearTimeout(toast._t);toast._t=setTimeout(function(){t.classList.remove("show");},2200);}
function closeMenus(){document.querySelectorAll(".dd.open").forEach(function(el){el.classList.remove("open");});}
function toggleMenu(id,e){if(e)e.stopPropagation();var el=document.getElementById(id);if(!el)return;var was=el.classList.contains("open");closeMenus();if(!was)el.classList.add("open");}
function filterDrop(id){var root=document.getElementById(id);if(!root)return;var q=((root.querySelector(".dd-search")||{}).value||"").toLowerCase();root.querySelectorAll("[data-filter]").forEach(function(item){var hay=(item.getAttribute("data-filter")||"").toLowerCase();item.style.display=hay.indexOf(q)>=0?"":"none";});}
function selectPath(pid){if(!validPath(pid))return;activePath=pid;activeModule=(TRAINING[pid].modules[0]||{}).id||null;save();closeMenus();renderAll();}
function selectModule(mid){if(!modules().some(function(m){return m.id===mid;}))return;activeModule=mid;save();closeMenus();renderAll();}
function renderPathDrop(){var p=pathData();var a=document.getElementById("pathBtnVal");var k=document.getElementById("pathBtnK");if(a)a.textContent=p?p.name:"Select path";if(k)k.textContent=p?p.level:"PATH";var list=document.getElementById("pathList");if(!list)return;list.innerHTML=PATHS.map(function(x){return '<button class="dd-item" data-filter="'+esc(x.name)+'" onclick="selectPath(\''+x.id+'\')">'+esc(x.level)+' - '+esc(x.name)+'</button>';}).join("");}
function renderModuleDrop(){var m=moduleData();var a=document.getElementById("modBtnVal");var k=document.getElementById("modBtnK");if(a)a.textContent=m?m.title:"Select module";if(k)k.textContent=m?m.phase:"MODULE";var list=document.getElementById("modList");if(!list)return;list.innerHTML=modules().map(function(mm,i){return '<button class="dd-item" data-filter="'+esc(mm.title)+'" onclick="selectModule(\''+mm.id+'\')">'+String(i+1).padStart(2,"0")+' '+esc(mm.title)+'</button>';}).join("");}
function renderModulesNav(){var q=((document.getElementById("search")||{}).value||"").toLowerCase();var host=document.getElementById("moduleList");if(!host)return;host.innerHTML=modules().filter(function(m){return (m.title+" "+m.phase).toLowerCase().indexOf(q)>=0;}).map(function(m,i){return '<button class="module" onclick="selectModule(\''+m.id+'\')">'+String(i+1).padStart(2,"0")+' '+esc(m.title)+'</button>';}).join("");}
function flatIndex(m,si,ci){var n=0;for(var i=0;i<si;i++)n+=((m.sections[i]&&m.sections[i][2])||[]).length;return n+ci;}
function nextModule(){var arr=modules(),i=arr.findIndex(function(m){return m.id===activeModule;});if(i<arr.length-1){activeModule=arr[i+1].id;save();renderAll();}else toast("End of this path");}
function renderMain(){var m=moduleData(),host=document.getElementById("main");if(!host)return;if(!m){host.innerHTML="<div>No module.</div>";return;}var saved=getChecks(m.id);var pd=pathData()||{level:"LEVEL 1"};
if(m.quiz){var quiz=(TRAINING[activePath]&&TRAINING[activePath].quiz)||[];host.innerHTML='<section class="card module-head"><h2>'+esc(m.title)+'</h2>'+(saved.score!=null?'<div class="note">LAST SCORE: '+saved.score+'%</div>':'')+'</section><section class="card" style="padding:16px;margin-top:10px">'+quiz.map(function(q,i){return '<div><strong>'+(i+1)+'. '+esc(q.q)+'</strong>'+q.a.map(function(ans,j){return '<label class="check"><input type="radio" name="q'+i+'" value="'+j+'" data-q="'+i+'"><span>'+esc(ans)+'</span></label>';}).join('')+'</div>';}).join('')+'<div class="footer-actions"><button class="btn primary" id="gradeBtn">Grade Quiz</button><button class="btn" id="nextBtn">Next Module</button></div></section>';
host.querySelectorAll("[data-q]").forEach(function(el){el.onchange=function(){saved.answers=saved.answers||{};saved.answers[el.getAttribute("data-q")]=Number(el.value);state.progress[moduleKey(m.id)]=saved;save();};});
host.querySelector("#gradeBtn").onclick=function(){var c=0;quiz.forEach(function(q,i){if(Number(saved.answers&&saved.answers[i])===q.correct)c++;});saved.score=quiz.length?Math.round(c/quiz.length*100):0;state.progress[moduleKey(m.id)]=saved;save();renderAll();toast(saved.score>=80?"Quiz passed":"Below 80%");};
host.querySelector("#nextBtn").onclick=nextModule;return;}
if(m.signoff){host.innerHTML='<section class="card module-head"><h2>'+esc(m.title)+'</h2></section><section class="card" style="padding:16px;margin-top:10px"><input id="signTech" class="text-input" placeholder="Technician"><input id="signSupervisor" class="text-input" placeholder="Supervisor"><input id="signDate" class="text-input" type="date"><div class="footer-actions"><button class="btn primary" id="signBtn">Complete Sign-Off</button></div></section>';
host.querySelector("#signBtn").onclick=function(){saved.fields={tech:host.querySelector("#signTech").value,supervisor:host.querySelector("#signSupervisor").value,date:host.querySelector("#signDate").value};saved.signoff=true;state.progress[moduleKey(m.id)]=saved;save();renderAll();toast("Sign-off saved");};return;}
var total=(m.sections||[]).reduce(function(a,s){return a+((s[2]||[]).length);},0);var checked=Object.keys(saved).filter(function(k){return saved[k]===true;}).length;var pct=total?Math.round(checked/total*100):0;
host.innerHTML='<section class="card module-head"><div class="kicker">'+esc(pd.level)+' // '+esc(m.phase)+'</div><h2>'+esc(m.title)+'</h2><p>'+esc(m.subtitle||'')+'</p><div class="progressbar"><i style="width:'+pct+'%"></i></div></section>'+(m.sections||[]).map(function(s,si){return '<section class="sec-acc"><button class="sec-btn" type="button" onclick="this.parentNode.classList.toggle(\'open\')"><h3>'+esc(s[0])+'</h3><div class="details">'+esc(s[1])+'</div></button><div class="sec-body">'+(s[2]||[]).map(function(c,ci){return '<label class="check"><input type="checkbox" data-check="'+si+':'+ci+'" '+(saved[flatIndex(m,si,ci)]?'checked':'')+'><span>'+esc(c)+'</span></label>';}).join('')+'</div></section>';}).join('')+'<div class="footer-actions"><button class="btn primary" id="completeBtn">Mark Remaining Complete</button><button class="btn" id="nextBtn">Next Module</button></div>';
host.querySelectorAll("[data-check]").forEach(function(el){el.onchange=function(){var parts=el.getAttribute("data-check").split(":");state.progress[moduleKey(m.id)]=state.progress[moduleKey(m.id)]||{};state.progress[moduleKey(m.id)][flatIndex(m,Number(parts[0]),Number(parts[1]))]=el.checked;save();renderAll();};});
host.querySelector("#completeBtn").onclick=function(){state.progress[moduleKey(m.id)]=state.progress[moduleKey(m.id)]||{};var i=0;(m.sections||[]).forEach(function(s){(s[2]||[]).forEach(function(){state.progress[moduleKey(m.id)][i++]=true;});});save();renderAll();toast("Module complete");};
host.querySelector("#nextBtn").onclick=nextModule;}
function resetProgress(){if(!confirm("Reset local progress?"))return;var pid=defaultPathId();state={path:pid,module:((TRAINING[pid]&&TRAINING[pid].modules)||[])[0]?TRAINING[pid].modules[0].id:null,progress:{}};activePath=pid;activeModule=state.module;save();renderAll();toast("Back on Level 1");}
function exportRecord(){var a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["HOOD BOSS KEC TRAINING"],{type:"text/plain"}));a.download="kec-training-record.txt";a.click();}
function updateStats(){var s=allStats();var mc=document.getElementById("moduleCount");var dc=document.getElementById("doneCount");if(mc)mc.textContent=s.ms;if(dc)dc.textContent=(s.ms?Math.round(s.done/s.ms*100):0)+"%";}
window.toggleMenu=toggleMenu;window.filterDrop=filterDrop;window.selectPath=selectPath;window.selectModule=selectModule;window.resetProgress=resetProgress;window.exportRecord=exportRecord;window.renderModulesNav=renderModulesNav;
