const DATA=window.__KEC_DATA__;
if(!DATA||!DATA.training){document.body.innerHTML="<div style='padding:24px;color:#00ff87'>Training data failed to load.</div>";throw new Error("KEC DATA missing");}
const PATHS=DATA.paths||[],TRAINING=DATA.training||{},KEY="hoodboss-kec-training-v12",MEMORY={value:null};
const STORAGE=(()=>{try{const t="__t";localStorage.setItem(t,"1");localStorage.removeItem(t);return localStorage;}catch(_){return null}})();
function readSaved(){try{if(STORAGE){const c=STORAGE.getItem(KEY);if(c)return c}return MEMORY.value}catch(_){return MEMORY.value}}
function writeSaved(v){MEMORY.value=v;try{if(STORAGE)STORAGE.setItem(KEY,v)}catch(_){}}
function validPath(id){return PATHS.some(p=>p.id===id)&&TRAINING[id]&&(TRAINING[id].modules||[]).length}
const DEFAULT_PATH="new-tech";
function defaultPathId(){return validPath(DEFAULT_PATH)?DEFAULT_PATH:((PATHS.find(x=>validPath(x.id))||PATHS[0]||{}).id)}
function blankState(){const pid=defaultPathId();return{path:pid,module:(TRAINING[pid]?.modules?.[0]?.id||null),progress:{},openPhases:{},openSecs:{}}}
function load(){try{const raw=readSaved(),x=raw?JSON.parse(raw):null;const base=blankState();if(!x||typeof x!=="object")return base;const m=Object.assign(base,x);let mgr=false;try{mgr=sessionStorage.getItem("hb-kec-mgr")==="1"}catch(_){}
if(!mgr||!validPath(m.path)){m.path=defaultPathId();const first=TRAINING[m.path]?.modules?.[0]?.id||null;if(!m.module||!(TRAINING[m.path]?.modules||[]).some(z=>z.id===m.module))m.module=first}return m}catch(_){return blankState()}}
let state=load();
let activePath=validPath(state.path)?state.path:blankState().path;
let activeModule=(TRAINING[activePath]?.modules||[]).some(m=>m.id===state.module)?state.module:(TRAINING[activePath]?.modules?.[0]?.id||null);
function save(){state.path=activePath;state.module=activeModule;writeSaved(JSON.stringify(state))}
function pathData(){return PATHS.find(p=>p.id===activePath)}
function modules(){return TRAINING[activePath]?.modules||[]}
function moduleData(){return modules().find(m=>m.id===activeModule)||modules()[0]}
function moduleKey(mid){return activePath+"::"+mid}
function getChecks(mid){return state.progress[moduleKey(mid)]||{}}
function moduleDone(mid){const m=modules().find(x=>x.id===mid);if(!m)return false;const s=getChecks(mid);if(m.quiz)return Number.isFinite(s.score)&&s.score>=80;if(m.signoff)return!!s.signoff;const c=(m.sections||[]).flatMap(z=>z[2]||[]);return c.length>0&&c.every((_,i)=>s[i])}
function esc(x){return String(x??"").replace(/[&<>"']/g,c=>({"&":"&","<":"<",">":">",'"':""","'":"&#39;"}[c]))}
function toast(msg){const t=document.getElementById("toast");if(!t)return;t.textContent=msg;t.classList.add("show");clearTimeout(toast._t);toast._t=setTimeout(()=>t.classList.remove("show"),2200)}
function closeMenus(){document.querySelectorAll(".dd.open").forEach(el=>el.classList.remove("open"))}
function toggleMenu(id,e){if(e)e.stopPropagation();const el=document.getElementById(id);const was=el.classList.contains("open");closeMenus();if(!was)el.classList.add("open")}
function filterDrop(id){const root=document.getElementById(id);const q=(root.querySelector(".dd-search")?.value||"").toLowerCase();root.querySelectorAll("[data-filter]").forEach(item=>{item.style.display=(item.getAttribute("data-filter")||"").toLowerCase().includes(q)?"":"none"})}
function selectPath(pid){if(!validPath(pid))return;activePath=pid;activeModule=TRAINING[pid].modules[0]?.id||null;save();closeMenus();renderAll()}
function selectModule(mid){if(!modules().some(m=>m.id===mid))return;activeModule=mid;save();closeMenus();renderAll()}
function renderPathDrop(){const p=pathData();const a=document.getElementById("pathBtnVal");const k=document.getElementById("pathBtnK");if(a)a.textContent=p?p.name:"Select path";if(k)k.textContent=p?p.level:"PATH";const list=document.getElementById("pathList");if(!list)return;list.innerHTML=PATHS.map(x=>`<button class="dd-item ${x.id===activePath?"active":""}" data-filter="${esc(x.level+" "+x.name)}" onclick="selectPath('${x.id}')"><strong>${esc(x.level)} · ${esc(x.name)}</strong></button>`).join("")}
function renderModuleDrop(){const m=moduleData();const a=document.getElementById("modBtnVal");const k=document.getElementById("modBtnK");if(a)a.textContent=m?m.title:"Select module";if(k)k.textContent=m?m.phase:"MODULE";const list=document.getElementById("modList");if(!list)return;list.innerHTML=modules().map((mm,i)=>`<button class="dd-item ${mm.id===activeModule?"active":""}" data-filter="${esc(mm.title)}" onclick="selectModule('${mm.id}')">${moduleDone(mm.id)?"✓":String(i+1).padStart(2,"0")} ${esc(mm.title)}</button>`).join("")}
function renderModulesNav(){const q=(document.getElementById("search")?.value||"").toLowerCase();const host=document.getElementById("moduleList");if(!host)return;host.innerHTML=modules().filter(m=>(m.title+" "+m.phase).toLowerCase().includes(q)).map((m,i)=>`<button class="module ${m.id===activeModule?"active":""}" onclick="selectModule('${m.id}')">${moduleDone(m.id)?"✓ ":""}${String(i+1).padStart(2,"0")} ${esc(m.title)}</button>`).join("")}
function flatIndex(m,si,ci){let n=0;for(let i=0;i<si;i++)n+=(m.sections[i][2]||[]).length;return n+ci}
function renderMain(){const m=moduleData(),host=document.getElementById("main");if(!host)return;if(!m){host.innerHTML='<div class="empty">No module.</div>';return}const saved=getChecks(m.id);
if(m.quiz){const quiz=TRAINING[activePath]?.quiz||[];host.innerHTML=`<section class="card module-head"><div class="kicker">${esc(pathData().level)} // ${esc(m.phase)}</div><h2>${esc(m.title)}</h2>${saved.score!=null?`<div class="note">LAST SCORE: ${saved.score}%</div>`:""}</section><section class="card" style="padding:16px;margin-top:10px">${quiz.map((q,i)=>`<div class="quiz-q"><strong>${i+1}. ${esc(q.q)}</strong>${q.a.map((a,j)=>`<label class="check"><input type="radio" name="q${i}" value="${j}" data-q="${i}" ${Number(saved.answers?.[i])===j?"checked":""}><span>${esc(a)}</span></label>`).join("")}</div>`).join("")}<div class="footer-actions"><button class="btn primary" id="gradeBtn">Grade Quiz</button><button class="btn" id="nextBtn">Next Module →</button></div></section>`;
host.querySelectorAll("[data-q]").forEach(el=>el.onchange=()=>{saved.answers=saved.answers||{};saved.answers[el.dataset.q]=Number(el.value);state.progress[moduleKey(m.id)]=saved;save()});
host.querySelector("#gradeBtn").onclick=()=>{let c=0;quiz.forEach((q,i)=>{if(Number(saved.answers?.[i])===q.correct)c++});saved.score=quiz.length?Math.round(c/quiz.length*100):0;state.progress[moduleKey(m.id)]=saved;save();renderAll();toast(saved.score>=80?"Quiz passed":"Below 80%")};
host.querySelector("#nextBtn").onclick=nextModule;return}
if(m.signoff){const f=saved.fields||{};host.innerHTML=`<section class="card module-head"><h2>${esc(m.title)}</h2></section><section class="card" style="padding:16px;margin-top:10px"><label class="check" style="flex-direction:column;align-items:stretch"><span>Technician</span><input id="signTech" class="text-input" value="${esc(f.tech||"")}"></label><label class="check" style="flex-direction:column;align-items:stretch"><span>Supervisor</span><input id="signSupervisor" class="text-input" value="${esc(f.supervisor||"")}"></label><label class="check" style="flex-direction:column;align-items:stretch"><span>Date</span><input id="signDate" class="text-input" type="date" value="${esc(f.date||new Date().toISOString().slice(0,10))}"></label><div class="footer-actions"><button class="btn primary" id="signBtn">Complete Sign-Off</button></div></section>`;
host.querySelector("#signBtn").onclick=()=>{saved.fields={tech:host.querySelector("#signTech").value,supervisor:host.querySelector("#signSupervisor").value,date:host.querySelector("#signDate").value};saved.signoff=true;state.progress[moduleKey(m.id)]=saved;save();renderAll();toast("Sign-off saved")};return}
const total=(m.sections||[]).flatMap(s=>s[2]||[]).length;const checked=Object.values(saved).filter(v=>v===true).length;const pct=total?Math.round(checked/total*100):0;
host.innerHTML=`<section class="card module-head"><div class="kicker">${esc(pathData().level)} // ${esc(m.phase)}</div><h2>${esc(m.title)}</h2><p>${esc(m.subtitle||"")}</p><div class="progressbar"><i style="width:${pct}%"></i></div></section>${(m.sections||[]).map((s,si)=>`<section class="sec-acc open"><button class="sec-btn" type="button" onclick="this.parentNode.classList.toggle('open')"><div><h3>${esc(s[0])}</h3><div class="details">${esc(s[1])}</div></div></button><div class="sec-body">${(s[2]||[]).map((c,ci)=>`<label class="check"><input type="checkbox" data-check="${si}:${ci}" ${saved[flatIndex(m,si,ci)]?"checked":""}><span>${esc(c)}</span></label>`).join("")}</div></section>`).join("")}<div class="footer-actions"><button class="btn primary" id="completeBtn">Mark Remaining Complete</button><button class="btn" id="nextBtn">Next Module →</button></div>`;
host.querySelectorAll("[data-check]").forEach(el=>el.onchange=()=>{const[si,ci]=el.dataset.check.split(":").map(Number);state.progress[moduleKey(m.id)]=state.progress[moduleKey(m.id)]||{};state.progress[moduleKey(m.id)][flatIndex(m,si,ci)]=el.checked;save();renderAll()});
host.querySelector("#completeBtn").onclick=()=>{state.progress[moduleKey(m.id)]=state.progress[moduleKey(m.id)]||{};let i=0;(m.sections||[]).forEach(s=>(s[2]||[]).forEach(()=>state.progress[moduleKey(m.id)][i++]=true));save();renderAll();toast("Module complete")};
host.querySelector("#nextBtn").onclick=nextModule}
function nextModule(){const arr=modules(),i=arr.findIndex(m=>m.id===activeModule);if(i<arr.length-1){activeModule=arr[i+1].id;save();renderAll()}else toast("End of this path")}
function resetProgress(){if(confirm("Reset local progress?")){const pid=defaultPathId();state={path:pid,module:TRAINING[pid]?.modules?.[0]?.id||null,progress:{}};activePath=pid;activeModule=state.module;save();renderAll();toast("Back on Level 1")}}
function exportRecord(){const text="HOOD BOSS KEC TRAINING\n"+PATHS.map(p=>p.name).join(", ");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type:"text/plain"}));a.download="kec-training-record.txt";a.click()}
function updateStats(){const ms=modules().length,done=modules().filter(m=>moduleDone(m.id)).length;const mc=document.getElementById("moduleCount");const dc=document.getElementById("doneCount");const cc=document.getElementById("checkCount");if(mc)mc.textContent=ms;if(dc)dc.textContent=(ms?Math.round(done/ms*100):0)+"%";if(cc)cc.textContent=done}
state.audience="tech";try{if(sessionStorage.getItem("hb-kec-mgr")==="1")state.audience="mgr"}catch(_){}
function isMgr(){return state.audience==="mgr"}
function closeGate(){document.getElementById("mgrGate")?.classList.remove("open")}
function toggleAudience(e){if(e)e.stopPropagation();if(isMgr()){state.audience="tech";try{sessionStorage.removeItem("hb-kec-mgr")}catch(_){}activePath=defaultPathId();activeModule=TRAINING[activePath]?.modules?.[0]?.id||null;save();renderAll();toast("Back to Level 1");return}document.getElementById("mgrGate")?.classList.add("open")}
function unlockManager(e){if(e)e.preventDefault();if(((document.getElementById("mgrPass")||{}).value||"").trim()!=="BOSS96"){const err=document.getElementById("mgrErr");if(err)err.textContent="Wrong code.";return}state.audience="mgr";try{sessionStorage.setItem("hb-kec-mgr","1")}catch(_){}closeGate();save();renderAll();toast("Manager unlocked")}
function renderAppDrop(){const host=document.getElementById("appList");if(!host)return;const apps=[{n:"Hood Boss Academy",u:"https://hbacademy.netlify.app/"},{n:"Field Tech Playbook",u:"https://hood-boss-field-playbook-4001xvgm9-antmanthepros-projects.vercel.app/"},{n:"MyTechPix Guide",u:"https://mytechpix-guide-for-techs.netlify.app/"}];host.innerHTML=apps.map(a=>`<a class="dd-item" href="${a.u}" target="_blank">${a.n}</a>`).join("")}
function renderAll(){renderPathDrop();renderModuleDrop();renderModulesNav();renderMain();updateStats();renderAppDrop();const av=document.getElementById("audVal");if(av)av.textContent=isMgr()?"Manager":"Technician"}
document.addEventListener("click",e=>{if(!e.target.closest(".dd"))closeMenus()});
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",renderAll,{once:true});else renderAll();
